### PR TITLE
fixed MPI PID attributions in ITI-38; fixed typo in "Manager"

### PR DESCRIPTION
**Pull request by unixoid**

### CODE REVIEW

**Review by oliveregger — COMMENTED** [review]
Thanks for catching the typos.

What is the reason for suggesting to fix the MPI PID attributions?

The sequence diagram is used in this test 

https://ehealthsuisse.ihe-europe.net/gazelle/testing/testsDefinition/viewTestPage.seam?id=13185&testKeyword=HP_gets_document_Patient_2of3

and follows the following step:

The Responding Gateway of the Other Community needs to handle Cross Patient Discovery Request (returning the MPI_B-PID or MPI_C-PID for the EPR-SPID, steps 27-32), to return the Cross Gateway Query Result (steps 33-40) and to perform a Cross Gateway Retrieve (steps 41, 48) returning the request document from the Document Repository (SS).

 in my view the sequence diagram should not be chagned.

**Comment by unixoid** [comment]
On [2_02_EPR_HPGetDocuments2of3.plantuml.txt](https://github.com/ahdis/ch-epr-seqdiag/pull/6/commits/0846c17081d26f9acce96808abf6142627f6a75a#diff-205f6c05abc0ffa839ef57e249554b99b7850c96fc7bf1c1c979b82457e24727):
From the first section ("documents within other communities from patient who has his reference community in another community") we learn that the red-light community is the assigner of MPI_A-PID, and the blue community -- the assigner of MPI_B-PID.
Then, in the section "Request from external community", the blue community wants to query/retrieve documents from the light-red community, and this means, the blue community has to query MPI_A-PID (steps 32-37) and use it in the ITI-38 call (steps 38-47).

On [step_pp_xds_reg_2of2.plantuml.txt](https://github.com/ahdis/ch-epr-seqdiag/pull/6/commits/0846c17081d26f9acce96808abf6142627f6a75a#diff-54803cda860d5baed4c6aeca03e9b3b6796139446bdd377eea7d2de0bd914841) (included from [2_02b_EPR_PatientGetDocuments2of2.plantuml.txt](https://github.com/ahdis/ch-epr-seqdiag/pull/6/commits/0846c17081d26f9acce96808abf6142627f6a75a#diff-df3e44ae38f6adb5db3792dccf126ee500971d22d58430672ae5487306574d24)):
In steps 19-24, the red-light community queries MPI_B-PID from the blue community, in order to use it in a subsequent ITI-38 call (steps 25-26).  In that way, it is absolutely impossible that MPI_A-PID is used instead of MPI_B-PID in the step 27.

**Comment by unixoid** [comment]
> this is not the intention of the diagram/test, it shows how the ITI-55 query for step 21,22 is resolving MPI-PIDB from EPRS-PID on the bottom part of the diagram within the external community itself. maybe we need to describe this more cleary, but the intention of this diagram is to support the test, and test states the 'Retrieve the MPI-PID of the patient in the remote communites'

Ok, let us assume that it is correct to use MPI_B-PID in step 38.  But then, why and how MPI_A-PID is used in step 40?

**Comment by oliveregger** [comment]
step 40 is an error, i agree, that should be MPI_B PID

**Comment by unixoid** [comment]
But the MPI-PID of the light-red community is MPI_A-PID, not MPI_B-PID.  See steps 06-08, for example.  It means, step 40 will fail with the error message "unknown patient ID".

**Comment by oliveregger** [comment]
no, this is also showing the iti-38 handling in the answering community, same as for iti-55

**Comment by unixoid** [comment]
How can it be that the MPI of the light-red community returns MPI_A-PID in step 08, but MPI_B-PID in step 35?

**Comment by oliveregger** [comment]
because in the bottom this is not the 'light red community' but the remote community described in the test (steps 32 and following).

**Comment by unixoid** [comment]
Ok, I got your point.  But it is still a little bit misleading to "substitute actors on the fly" in a continuous sequence diagram -- in particular if one uses the diagram not to perform a Projectathon test, but to generally understand EPR mechanisms (like my colleagues did).

**Comment by oliveregger** [comment]
agree that we need add wording to clarify the bottom better.

**Comment by oliveregger** [comment]
@unixoid is the wording now clearer?

**Comment by unixoid** [comment]
@oliveregger Yes, thank you.  I rephrased it a little bit and changed the layout.

**Pull request merged**
